### ISSUE TITLE
release 一个编译好的版本

### ISSUE THREAD

**Issue by ctaoist** [ldm0/rspleeter#1]
从源码编译失败了

```
error: failed to run custom build command for `rusty_ffmpeg v0.9.5`

Caused by:
  process didn't exit successfully: `/home/liaoyuanfang/projects/rust/rspleeter/target/debug/build/rusty_ffmpeg-fca6c94e3a6b62ef/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'No linking method set!', /home/liaoyuanfang/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/rusty_ffmpeg-0.9.5/build.rs:339:13
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

建议说清楚编译的要求，我觉得应该有两种:

- 一种是只编译 rspleeter 二进制
- 另一种连带 ffmpeg 一起编译，我也只找到这种的说明

**Comment by ldm0** [comment]
可以提供一下上下文嘛，使用的是否是`cargo xtask xxx`
目前编译的要求是:
1. 如果没有使用prebuilt_ffmpeg，会在编译rspleeter的过程中自动帮你编译一个ffmpeg
2. 如果使用了prebuilt_ffmpeg，编译rspleeter的过程中就直接链接给定的dylib

**Comment by ldm0** [comment]
如果不想自己编译FFmpeg，可以看<https://github.com/ldm0/rspleeter#ffmpeg-dylib>这小节的指引，下载预编译的FFmpeg dylib。各个平台都测试过，应该不会有问题。

关于release编译好的版本，我下班之后来操作一下。

**Comment by ctaoist** [comment]
系统：Linux 5.13.0-39-generic #44~20.04.1-Ubuntu x86_64 GNU/Linux
gcc version: gcc (Ubuntu 7.5.0-6ubuntu2) 7.5.0
rust version: rustc 1.60.0 (7737e0b5c 2022-04-04)

使用了prebuilt_ffmpeg之后提示找不到 libclang.so，使用conda安装的libclang，版本10.0.1

```
error: failed to run custom build command for `rusty_ffmpeg v0.9.5`

Caused by:
  process didn't exit successfully: `/home/liaoyuanfang/projects/rust/rspleeter/target/release/build/rusty_ffmpeg-33ba149b2a98fd63/build-script-build` (exit status: 101)
  --- stdout
  cargo:rustc-link-lib=dylib=ffmpeg
  cargo:rustc-link-search=native=/home/liaoyuanfang/projects/rust/rspleeter/prebuilt_ffmpeg/lib

  --- stderr
  /usr/include/limits.h:124:16: fatal error: 'limits.h' file not found
  thread 'main' panicked at 'Binding generation failed.: ClangDiagnostic("/usr/include/limits.h:124:16: fatal error: 'limits.h' file not found\n")', /home/liaoyuanfang/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/rusty_ffmpeg-0.9.5/build.rs:157:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed
```

`/usr/include/limits.h:124`:

```c
#if defined __GNUC__ && !defined _GCC_LIMITS_H_
/* `_GCC_LIMITS_H_' is what GCC's file defines.  */
# include_next <limits.h>
#endif
```

应该是找不到gcc的`limits.h`.

**Comment by ldm0** [comment]
简单搜索了一下，你使用的clang本身的环境比较可疑。
https://github.com/lvzixun/Clang-Complete/issues/13
https://stackoverflow.com/questions/30877659/fatal-error-limits-h-no-such-file-or-directory
https://stackoverflow.com/questions/29567990/gmock-clang-pesky-error-usr-include-limits-h12316-fatal-error-limits-h-f

建议试下 apt 安装 libclang-dev

**Comment by ctaoist** [comment]
我等你编译好的吧，linux机器不是我一个人在用

**Comment by vimcdoe** [comment]
试了可以用
```bash
./rspleeter ./input/ten_years.mp3 ./output/  
Input #0, mp3, from './input/ten_years.mp3':
  Metadata:
    encoder         : Lavf59.16.100
  Duration: 00:03:24.67, start: 0.025057, bitrate: 128 kb/s
  Stream #0:0: Audio: mp3, 44100 Hz, stereo, s16p, 128 kb/s
    Metadata:
      encoder         : Lavc59.18
    Side data:
      replaygain: track gain - -6.800000, track peak - unknown, album gain - unknown, album peak - unknown, 
[mp3 @ 0x55555afc7080] Could not update timestamps for skipped samples.
[mp3 @ 0x55555afc7080] Could not update timestamps for discarded samples.
2022-06-20T08:12:01.169403Z  INFO rspleeter::splitter: tensorflow_version="2.8.0-dev20220131"
2022-06-20 16:12:01.188281: I tensorflow/cc/saved_model/reader.cc:43] Reading SavedModel from: models/2stems
2022-06-20 16:12:01.200342: I tensorflow/cc/saved_model/reader.cc:78] Reading meta graph with tags { serve }
2022-06-20 16:12:01.200398: I tensorflow/cc/saved_model/reader.cc:119] Reading SavedModel debug info (if present) from: models/2stems
2022-06-20 16:12:01.200499: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-06-20 16:12:01.344321: I tensorflow/cc/saved_model/loader.cc:228] Restoring SavedModel bundle.
2022-06-20 16:12:01.542434: I tensorflow/cc/saved_model/loader.cc:212] Running initialization op on SavedModel bundle at path: models/2stems
2022-06-20 16:12:01.565567: I tensorflow/cc/saved_model/loader.cc:301] SavedModel load for tags { serve }; Status: success: OK. Took 377296 microseconds.
2022-06-20T08:12:01.668440Z  INFO rspleeter::splitter: processing: [0, 1543500), using [0, 1323000)
2022-06-20 16:12:02.235667: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 49414144 exceeds 10% of free system memory.
2022-06-20 16:12:02.252533: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 49438272 exceeds 10% of free system memory.
2022-06-20 16:12:02.254675: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 98828288 exceeds 10% of free system memory.
2022-06-20 16:12:04.070341: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 49438272 exceeds 10% of free system memory.
2022-06-20 16:12:04.087636: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 50356224 exceeds 10% of free system memory.
2022-06-20T08:12:07.931077Z  INFO rspleeter::splitter: 1/7 done...
2022-06-20T08:12:07.931620Z  INFO rspleeter::splitter: processing: [1102500, 2866500), using [1323000, 2646000)
2022-06-20T08:12:14.591070Z  INFO rspleeter::splitter: 2/7 done...
2022-06-20T08:12:14.591098Z  INFO rspleeter::splitter: processing: [2425500, 4189500), using [2646000, 3969000)
2022-06-20T08:12:21.252944Z  INFO rspleeter::splitter: 3/7 done...
2022-06-20T08:12:21.252970Z  INFO rspleeter::splitter: processing: [3748500, 5512500), using [3969000, 5292000)
2022-06-20T08:12:27.885002Z  INFO rspleeter::splitter: 4/7 done...
2022-06-20T08:12:27.885030Z  INFO rspleeter::splitter: processing: [5071500, 6835500), using [5292000, 6615000)
2022-06-20T08:12:34.525115Z  INFO rspleeter::splitter: 5/7 done...
2022-06-20T08:12:34.525141Z  INFO rspleeter::splitter: processing: [6394500, 8158500), using [6615000, 7938000)
2022-06-20T08:12:41.138473Z  INFO rspleeter::splitter: 6/7 done...
2022-06-20T08:12:41.141895Z  INFO rspleeter::splitter: processing: [7717500, 9024644), using [7938000, 9024644)
2022-06-20T08:12:46.065897Z  INFO rspleeter::splitter: 7/7 done...
2022-06-20T08:12:46.111414Z  INFO rspleeter: Writing: ./output/vocals.mp3
2022-06-20T08:12:48.981066Z  INFO rspleeter: Writing: ./output/accompaniment.mp3

tree .
.
├── input
│   └── ten_years.mp3
├── libbz2.so.1.0
├── libc.so.6
├── libdl.so.2
├── libffmpeg.so
├── libgcc_s.so.1
├── libmp3lame.so.0
├── libm.so.6
├── libpthread.so.0
├── librt.so.1
├── libstdc++.so.6
├── libtensorflow_framework.so.2
├── libtensorflow.so.2
├── models
│   ├── 2stems
│   │   ├── saved_model.pb
│   │   └── variables
│   │       ├── variables.data-00000-of-00001
│   │       └── variables.index
│   ├── 4stems
│   │   ├── saved_model.pb
│   │   └── variables
│   │       ├── variables.data-00000-of-00001
│   │       └── variables.index
│   └── 5stems
│       ├── saved_model.pb
│       └── variables
│           ├── variables.data-00000-of-00001
│           └── variables.index
├── output
│   ├── accompaniment.mp3
│   └── vocals.mp3
└── rspleeter

ldd rspleeter 
	linux-vdso.so.1 (0x00007ffd9ad4d000)
	libtensorflow_framework.so.2 (0x00007f1bca2b2000)
	libtensorflow.so.2 (0x00007f1bbb792000)
	libffmpeg.so (0x00007f1bbb04b000)
	libgcc_s.so.1 (0x00007f1bbb030000)
	libpthread.so.0 (0x00007f1bbb00d000)
	libc.so.6 (0x00007f1bbae19000)
	libdl.so.2 (0x00007f1bbae13000)
	libm.so.6 (0x00007f1bbacc4000)
	librt.so.1 (0x00007f1bbacba000)
	libstdc++.so.6 (0x00007f1bbaad8000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f1bcc39f000)
	libmp3lame.so.0 (0x00007f1bbaa60000)
	libbz2.so.1.0 (0x00007f1bbaa4b000)


```

**Comment by ldm0** [comment]
@ctaoist  New release: https://github.com/ldm0/rspleeter/releases/tag/0.1.0

**Comment by ctaoist** [comment]
非常感谢。

**Comment by ldm0** [comment]
久等了。Feel free to reopen this issue if the new release is not working. : D
