### ISSUE TITLE
Again failed to custom build rusty_ffmpeg

### ISSUE THREAD

**Issue by ledunguit** [ldm0/rspleeter#3]
Sorry for inconvenience, for a month ago, I have built the project successfully, but up to now I got another error when I try to rebuild whole project.

System: Macos Ventura - Apple M2 Pro

Is this error relevant with the Rust bindgen problem?

The whole build log error is here:
```
error: failed to run custom build command for `rusty_ffmpeg v0.9.5`
note: To improve backtraces for build dependencies, set the CARGO_PROFILE_RELEASE_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.

Caused by:
  process didn't exit successfully: `/Users/ledangdung/Works/rspleeter/target/release/build/rusty_ffmpeg-15a22ce462393ed5/build-script-build` (exit status: 101)
  --- stdout
  cargo:rustc-link-lib=dylib=ffmpeg
  cargo:rustc-link-search=native=/Users/ledangdung/Works/rspleeter/target/ffmpeg_build/lib

  --- stderr
  thread 'main' panicked at /Users/ledangdung/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.39/src/fallback.rs:700:9:
  "wait_struct_(unnamed_at_/Library/Developer/CommandLineTools/SDKs/MacOSX_sdk/usr/include/sys/wait_h_199_2)" is not a valid Ident
  stack backtrace:
     0:        0x104b4b080 - std::backtrace_rs::backtrace::libunwind::trace::hf755a955ad018943
                                 at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
     1:        0x104b4b080 - std::backtrace_rs::backtrace::trace_unsynchronized::hde69ab8e2b667964
                                 at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
     2:        0x104b4b080 - std::sys_common::backtrace::_print_fmt::hf6c414569af631f5
                                 at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys_common/backtrace.rs:67:5
     3:        0x104b4b080 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h0524bd1b527203b8
                                 at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys_common/backtrace.rs:44:22
     4:        0x104b69454 - core::fmt::rt::Argument::fmt::ha0532872e39381ee
                                 at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/fmt/rt.rs:138:9
     5:        0x104b69454 - core::fmt::write::h74be1333b0a6ddea
                                 at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/fmt/mod.rs:1114:21
     6:        0x104b4837c - std::io::Write::write_fmt::h6c011b665b2d7d4b
                                 at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/io/mod.rs:1763:15
     7:        0x104b4aec0 - std::sys_common::backtrace::_print::hcc60dadc0e4df78f
                                 at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys_common/backtrace.rs:47:5
     8:        0x104b4aec0 - std::sys_common::backtrace::print::he25ff7dac6402434
                                 at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys_common/backtrace.rs:34:9
     9:        0x104b4c6dc - std::panicking::default_hook::{{closure}}::h41763ba018b93bf7
                                 at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:272:22
    10:        0x104b4c3f4 - std::panicking::default_hook::h017c44660373840e
                                 at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:292:9
    11:        0x104b4cc20 - std::panicking::rust_panic_with_hook::h221a0baf52ecd48a
                                 at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:731:13
    12:        0x104b4cb28 - std::panicking::begin_panic_handler::{{closure}}::h18b661cf0f97a414
                                 at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:609:13
    13:        0x104b4b50c - std::sys_common::backtrace::__rust_end_short_backtrace::h4f4b2ffab2311217
                                 at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys_common/backtrace.rs:170:18
    14:        0x104b4c894 - rust_begin_unwind
                                 at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:597:5
    15:        0x104b7ca78 - core::panicking::panic_fmt::hd6070cd222575be5
                                 at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/panicking.rs:72:14
    16:        0x104b10e8c - proc_macro2::fallback::validate_ident::h0a82accebfeb3d15
    17:        0x104b10ca4 - proc_macro2::fallback::Ident::_new::hda750219aac1fc90
    18:        0x104b10cf4 - proc_macro2::fallback::Ident::new::h050fd00d1486c5e8
    19:        0x104b12c40 - proc_macro2::imp::Ident::new::h241d736376dc5285
    20:        0x104b0d35c - proc_macro2::Ident::new::h08392fe25f3fb0d5
    21:        0x1048e3b50 - bindgen::ir::context::BindgenContext::rust_ident_raw::h647fc219b7dae70d
    22:        0x1048e3934 - bindgen::ir::context::BindgenContext::rust_ident::h095689de8d2bee36
    23:        0x104939f08 - <bindgen::ir::comp::CompInfo as bindgen::codegen::CodeGenerator>::codegen::hf976e3fdbe53bf13
    24:        0x104907358 - <bindgen::ir::ty::Type as bindgen::codegen::CodeGenerator>::codegen::he40fcaf5a7632b85
    25:        0x1048843b8 - <bindgen::ir::item::Item as bindgen::codegen::CodeGenerator>::codegen::he782151260874216
    26:        0x10493f710 - <bindgen::ir::comp::CompInfo as bindgen::codegen::CodeGenerator>::codegen::hf976e3fdbe53bf13
    27:        0x104907358 - <bindgen::ir::ty::Type as bindgen::codegen::CodeGenerator>::codegen::he40fcaf5a7632b85
    28:        0x1048843b8 - <bindgen::ir::item::Item as bindgen::codegen::CodeGenerator>::codegen::he782151260874216
    29:        0x1048b5b98 - <bindgen::ir::module::Module as bindgen::codegen::CodeGenerator>::codegen::{{closure}}::hb3efc3907f7105fa
    30:        0x1048c9cdc - <bindgen::ir::module::Module as bindgen::codegen::CodeGenerator>::codegen::h46b101bf772abbdb
    31:        0x1048843a0 - <bindgen::ir::item::Item as bindgen::codegen::CodeGenerator>::codegen::he782151260874216
    32:        0x1048bed5c - bindgen::codegen::codegen::{{closure}}::hcc67823fb974802b
    33:        0x1048e5884 - bindgen::ir::context::BindgenContext::gen::h003f428df5c958a6
    34:        0x1048be4c8 - bindgen::codegen::codegen::ha88168cde3501e82
    35:        0x1048d4fe0 - bindgen::Bindings::generate::h8bc2711016a8b1ff
    36:        0x1048d2e74 - bindgen::Builder::generate::h00d7f43999415bed
    37:        0x1047f9968 - build_script_build::generate_bindings::hd72ded90ea45b68f
    38:        0x1047fa430 - build_script_build::dynamic_linking::h0f174cdbeb1bbc2f
    39:        0x1047faca4 - build_script_build::main::h24ee95f15a35924a
    40:        0x1047f5880 - core::ops::function::FnOnce::call_once::h927b6a46b8252cdf
    41:        0x1047f5334 - std::sys_common::backtrace::__rust_begin_short_backtrace::hd52283daee44043e
    42:        0x1047fb9e4 - std::rt::lang_start::{{closure}}::hc89d1780faaf2a88
    43:        0x104b448b4 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h44482c562109b08c
                                 at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/ops/function.rs:284:13
    44:        0x104b448b4 - std::panicking::try::do_call::h627d61d518625eaf
                                 at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:504:40
    45:        0x104b448b4 - std::panicking::try::h487b8df834773e7d
                                 at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:468:19
    46:        0x104b448b4 - std::panic::catch_unwind::h5d4366c6f71d3443
                                 at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panic.rs:142:14
    47:        0x104b448b4 - std::rt::lang_start_internal::{{closure}}::h749338e1cc06c4f7
                                 at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/rt.rs:148:48
    48:        0x104b448b4 - std::panicking::try::do_call::h2098bd254e5cae95
                                 at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:504:40
    49:        0x104b448b4 - std::panicking::try::h7bfd8a0246bca0f8
                                 at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:468:19
    50:        0x104b448b4 - std::panic::catch_unwind::h6da51257cc975c65
                                 at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panic.rs:142:14
    51:        0x104b448b4 - std::rt::lang_start_internal::h5f00c09289a72e67
                                 at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/rt.rs:148:20
    52:        0x1047fb9c0 - std::rt::lang_start::hce0437209e0486a3
    53:        0x1047fad50 - _main
```

**Comment by ldm0** [comment]
Relevant issue: <https://github.com/rust-lang/rust-bindgen/issues/2700>. Seems to be a compatibility issue with bindgen and clang 16. I'll bump bindgen for rusty_ffmpeg later.

**Comment by ldm0** [comment]
Fixed
